[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/frame"
  to = "/.netlify/functions/frame"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"

# Ensure .well-known directory is published
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.images]
  compress = false