[build]
  publish = "dist"
  command = "npm run build"

# Redirect all routes to index.html for SPA client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Ensure .well-known directory is accessible
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

# Handle API routes for serverless functions (if needed later)
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

[build.environment]
  NODE_VERSION = "18"

# Ensure .well-known directory is published
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.images]
  compress = false